### ISSUE TITLE
S8 Sources - missing items

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/d2-additional-info#70] opened 2019-10-28 12:11 UTC
https://github.com/DestinyItemManager/d2-additional-info/pull/69

S8 Sources is missing items that have same names, but different hashes, that also do not have source info.

E.g. [Sword Flight](https://data.destinysets.com/i/InventoryItem:3298826188), [Substitional Alloy](https://data.destinysets.com/i/InventoryItem:2468603405), [Phoenix Strife](https://data.destinysets.com/i/InventoryItem:1742940528)

**Comment by sundevour** [comment] 2019-10-28 14:26
phoenix strife is detecting properly with `crucible` for me
![image](https://user-images.githubusercontent.com/31990469/67686414-e587e100-f953-11e9-80bb-e7c7a84b70ec.png)

substitutional alloy is not a s8 dupe of an older set and is also already detecting correctly for me under `vexoffensive`

i will fix `crucible`->swordflight but also yuck who wants that set even

**Comment by delphiactual** [comment] 2019-10-28 14:37
Crucible is in the description for Phoenix strife.

As for substitutional alloy I was looking at source:seasonpass

**Comment by sundevour** [comment] 2019-10-28 14:39
wow still asleep. okie doke.

**Closed** 2020-05-15 01:30 UTC
